version: '3.8'

services:
  jira:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/jira
        DB_USERNAME: jira
        DB_PASSWORD: JiraRush
        OAUTH2_GITHUB_CLIENT_ID: 3d0d8738e65881fff266
        OAUTH2_GITHUB_CLIENT_SECRET: 0f97031ce6178b7dfb67a6af587f37e222a16120
        OAUTH2_GOOGLE_CLIENT_ID: 329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com
        OAUTH2_GOOGLE_CLIENT_SECRET: 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
        OAUTH2_GITLAB_CLIENT_ID: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
        OAUTH2_GITLAB_CLIENT_SECRET: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
        MAIL_USERNAME: jira4jr@gmail.com
        MAIL_PASSWORD: zdfzsrqvgimldzyj
    ports:
      - "8080:8080"

  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources:/opt/jirarush/resources

  postgres-db-test:
    container_name: postgres-db-test
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira-test
    restart: unless-stopped
