version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    restart: unless-stopped

  postgres-db-test:
    container_name: postgres-db-test
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira-test
    restart: unless-stopped
